### PR TITLE
Building the Website

### PR DESCRIPTION
**Pull request by trentwirth**
sending comments via DM

### CODE REVIEW

**Comment by trentwirth** [comment]
- I merged "Contribute" into the Donate tab and called it "Get Involved", listing a handful of ways for people to contribute to the freemocap project. Make sure you're happy with those avenues of interaction 🙂

**Comment by trentwirth** [comment]
- The main color of the website is good, and connected to freemocap's color scheme already, but it makes the links on the page a little dark. I improved the UI a bit by making linked text bold, and calling out hyperlinks as such in many of the places they appear. LMK if you think any of that needs workshopped.

**Comment by trentwirth** [comment]
- The first half of the donation portals all explicitly say "The FreeMoCap Foundation", but the latter three say "FreeMoCap Project". This website distinctly IDs them as separate entities. 
-- Connected to this, we should probably remove the donation page from the freemocap website, or at least rephrase it so that it correctly calls out that the project isn't the foundation.

**Comment by trentwirth** [comment]
- If you could review the summaries I have of our "People", that would be great. I put things together, including linking public profiles, based on everyone's online presence. Once you've OK'd this and we merge the branch, we'll need to reach out to Endurance and Ryan to get their stamp of approval
-- I wasn't sure what order to put people in; I think that objectively the order should be Jon, Trent, Ryan, Endurance - ranked in order of titular involvement. I initially had it: Jon, Endurance, Ryan, Trent - for no particular reason. If you have opinions, ordering us is easy to switch around

**Review by jonmatthis — APPROVED** [review]
it good ✨

**Pull request merged**
